name: multinterp-dev
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - numba
  - cupy
  - matplotlib
  - jupyter
  - jupyterlab
  - scikit-learn
  - scikit-image
  - pytest
  - pip
  - pip:
      - git+https://github.com/alanlujan91/HARK@map_coordinates
